name: kakeibo_ui
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  graphql_flutter: 5.1.2
  get_it: ^7.1.4
  syncfusion_flutter_datepicker: ^19.4.42
  flutter_spinkit: ^5.1.0
  flutter_dotenv: ^5.0.2
  provider: ^6.0.0
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  charts_flutter: ^0.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/
    - .env.development
    - .env.production

  fonts:
    - family: BillionDreams
      fonts:
        - asset: assets/fonts/BillionDreams-Regular.ttf
